version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-affiliate-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-affiliate}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-affiliate123}
      POSTGRES_DB: ${DB_NAME:-ai_affiliate_empire}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-affiliate}']
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:latest
    container_name: ai-affiliate-temporal
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${DB_USER:-affiliate}
      - POSTGRES_PWD=${DB_PASSWORD:-affiliate123}
      - POSTGRES_SEEDS=postgres
    ports:
      - '7233:7233' # Temporal server
      - '8233:8233' # Temporal UI
    healthcheck:
      test: ['CMD', 'tctl', 'cluster', 'health']
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-affiliate-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      temporal:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${DB_USER:-affiliate}:${DB_PASSWORD:-affiliate123}@postgres:5432/${DB_NAME:-ai_affiliate_empire}?schema=public
      TEMPORAL_ADDRESS: temporal:7233

      # API Keys (set in .env)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      AMAZON_ACCESS_KEY: ${AMAZON_ACCESS_KEY}
      AMAZON_SECRET_KEY: ${AMAZON_SECRET_KEY}
      AMAZON_PARTNER_TAG: ${AMAZON_PARTNER_TAG}
      PIKALABS_API_KEY: ${PIKALABS_API_KEY}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
      DALLE_API_KEY: ${DALLE_API_KEY}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      TIKTOK_API_KEY: ${TIKTOK_API_KEY}
      INSTAGRAM_API_KEY: ${INSTAGRAM_API_KEY}

      # Monitoring
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT:-production}
      SENTRY_TRACES_SAMPLE_RATE: ${SENTRY_TRACES_SAMPLE_RATE:-0.1}
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: ai-affiliate-dashboard
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
    ports:
      - '3001:3001'

  prometheus:
    image: prom/prometheus:latest
    container_name: ai-affiliate-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    depends_on:
      - backend
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:9090/-/healthy']
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: ai-affiliate-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_ROOT_URL=http://localhost:3002
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - '3002:3000'
    depends_on:
      - prometheus
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3

  alertmanager:
    image: prom/alertmanager:latest
    container_name: ai-affiliate-alertmanager
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    ports:
      - '9093:9093'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:9093/-/healthy']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  default:
    name: ai-affiliate-network
