global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical'
      continue: true
    - match:
        severity: warning
      receiver: 'warning'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://backend:3000/webhooks/alerts'
        send_resolved: true

  - name: 'critical'
    webhook_configs:
      - url: 'http://backend:3000/webhooks/alerts/critical'
        send_resolved: true
    # Uncomment and configure for email alerts
    # email_configs:
    #   - to: 'alerts@example.com'
    #     from: 'alertmanager@example.com'
    #     smarthost: 'smtp.gmail.com:587'
    #     auth_username: 'your-email@gmail.com'
    #     auth_password: 'your-app-password'

  - name: 'warning'
    webhook_configs:
      - url: 'http://backend:3000/webhooks/alerts/warning'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'component']
