# Fly.io Production Configuration
app = "ai-affiliate-empire"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2  # Higher availability for production
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 500
    soft_limit = 400

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"  # More frequent health checks
  method = "GET"
  timeout = "5s"
  path = "/health"

  [http_service.checks.headers]
    Content-Type = "application/json"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

# Multi-region setup for high availability
[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024

[metrics]
  port = 9091
  path = "/metrics"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"

# Blue-green deployment strategy
[deploy]
  strategy = "bluegreen"
  max_unavailable = 0.2

# Auto-scaling configuration
[scaling]
  min_machines = 2
  max_machines = 10

[mounts]
  source = "data"
  destination = "/data"

# Backup configuration
[backup]
  schedule = "0 2 * * *"  # Daily at 2 AM UTC
  retention = 30  # Keep backups for 30 days
